/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.berkeley.cs.amplab.carat.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-02-14")
public class CallInfo implements org.apache.thrift.TBase<CallInfo, CallInfo._Fields>, java.io.Serializable, Cloneable, Comparable<CallInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CallInfo");

  private static final org.apache.thrift.protocol.TField INCOMING_CALL_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("incomingCallTime", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField OUTGOING_CALL_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("outgoingCallTime", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField NON_CALL_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("nonCallTime", org.apache.thrift.protocol.TType.DOUBLE, (short)3);
  private static final org.apache.thrift.protocol.TField CALL_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("callStatus", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CallInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CallInfoTupleSchemeFactory();

  public double incomingCallTime; // optional
  public double outgoingCallTime; // optional
  public double nonCallTime; // optional
  public java.lang.String callStatus; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INCOMING_CALL_TIME((short)1, "incomingCallTime"),
    OUTGOING_CALL_TIME((short)2, "outgoingCallTime"),
    NON_CALL_TIME((short)3, "nonCallTime"),
    CALL_STATUS((short)4, "callStatus");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INCOMING_CALL_TIME
          return INCOMING_CALL_TIME;
        case 2: // OUTGOING_CALL_TIME
          return OUTGOING_CALL_TIME;
        case 3: // NON_CALL_TIME
          return NON_CALL_TIME;
        case 4: // CALL_STATUS
          return CALL_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __INCOMINGCALLTIME_ISSET_ID = 0;
  private static final int __OUTGOINGCALLTIME_ISSET_ID = 1;
  private static final int __NONCALLTIME_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.INCOMING_CALL_TIME,_Fields.OUTGOING_CALL_TIME,_Fields.NON_CALL_TIME,_Fields.CALL_STATUS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INCOMING_CALL_TIME, new org.apache.thrift.meta_data.FieldMetaData("incomingCallTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.OUTGOING_CALL_TIME, new org.apache.thrift.meta_data.FieldMetaData("outgoingCallTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.NON_CALL_TIME, new org.apache.thrift.meta_data.FieldMetaData("nonCallTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CALL_STATUS, new org.apache.thrift.meta_data.FieldMetaData("callStatus", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CallInfo.class, metaDataMap);
  }

  public CallInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CallInfo(CallInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    this.incomingCallTime = other.incomingCallTime;
    this.outgoingCallTime = other.outgoingCallTime;
    this.nonCallTime = other.nonCallTime;
    if (other.isSetCallStatus()) {
      this.callStatus = other.callStatus;
    }
  }

  public CallInfo deepCopy() {
    return new CallInfo(this);
  }

  @Override
  public void clear() {
    setIncomingCallTimeIsSet(false);
    this.incomingCallTime = 0.0;
    setOutgoingCallTimeIsSet(false);
    this.outgoingCallTime = 0.0;
    setNonCallTimeIsSet(false);
    this.nonCallTime = 0.0;
    this.callStatus = null;
  }

  public double getIncomingCallTime() {
    return this.incomingCallTime;
  }

  public CallInfo setIncomingCallTime(double incomingCallTime) {
    this.incomingCallTime = incomingCallTime;
    setIncomingCallTimeIsSet(true);
    return this;
  }

  public void unsetIncomingCallTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __INCOMINGCALLTIME_ISSET_ID);
  }

  /** Returns true if field incomingCallTime is set (has been assigned a value) and false otherwise */
  public boolean isSetIncomingCallTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __INCOMINGCALLTIME_ISSET_ID);
  }

  public void setIncomingCallTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __INCOMINGCALLTIME_ISSET_ID, value);
  }

  public double getOutgoingCallTime() {
    return this.outgoingCallTime;
  }

  public CallInfo setOutgoingCallTime(double outgoingCallTime) {
    this.outgoingCallTime = outgoingCallTime;
    setOutgoingCallTimeIsSet(true);
    return this;
  }

  public void unsetOutgoingCallTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OUTGOINGCALLTIME_ISSET_ID);
  }

  /** Returns true if field outgoingCallTime is set (has been assigned a value) and false otherwise */
  public boolean isSetOutgoingCallTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OUTGOINGCALLTIME_ISSET_ID);
  }

  public void setOutgoingCallTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OUTGOINGCALLTIME_ISSET_ID, value);
  }

  public double getNonCallTime() {
    return this.nonCallTime;
  }

  public CallInfo setNonCallTime(double nonCallTime) {
    this.nonCallTime = nonCallTime;
    setNonCallTimeIsSet(true);
    return this;
  }

  public void unsetNonCallTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __NONCALLTIME_ISSET_ID);
  }

  /** Returns true if field nonCallTime is set (has been assigned a value) and false otherwise */
  public boolean isSetNonCallTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __NONCALLTIME_ISSET_ID);
  }

  public void setNonCallTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __NONCALLTIME_ISSET_ID, value);
  }

  public java.lang.String getCallStatus() {
    return this.callStatus;
  }

  public CallInfo setCallStatus(java.lang.String callStatus) {
    this.callStatus = callStatus;
    return this;
  }

  public void unsetCallStatus() {
    this.callStatus = null;
  }

  /** Returns true if field callStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetCallStatus() {
    return this.callStatus != null;
  }

  public void setCallStatusIsSet(boolean value) {
    if (!value) {
      this.callStatus = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case INCOMING_CALL_TIME:
      if (value == null) {
        unsetIncomingCallTime();
      } else {
        setIncomingCallTime((java.lang.Double)value);
      }
      break;

    case OUTGOING_CALL_TIME:
      if (value == null) {
        unsetOutgoingCallTime();
      } else {
        setOutgoingCallTime((java.lang.Double)value);
      }
      break;

    case NON_CALL_TIME:
      if (value == null) {
        unsetNonCallTime();
      } else {
        setNonCallTime((java.lang.Double)value);
      }
      break;

    case CALL_STATUS:
      if (value == null) {
        unsetCallStatus();
      } else {
        setCallStatus((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case INCOMING_CALL_TIME:
      return getIncomingCallTime();

    case OUTGOING_CALL_TIME:
      return getOutgoingCallTime();

    case NON_CALL_TIME:
      return getNonCallTime();

    case CALL_STATUS:
      return getCallStatus();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case INCOMING_CALL_TIME:
      return isSetIncomingCallTime();
    case OUTGOING_CALL_TIME:
      return isSetOutgoingCallTime();
    case NON_CALL_TIME:
      return isSetNonCallTime();
    case CALL_STATUS:
      return isSetCallStatus();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof CallInfo)
      return this.equals((CallInfo)that);
    return false;
  }

  public boolean equals(CallInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_incomingCallTime = true && this.isSetIncomingCallTime();
    boolean that_present_incomingCallTime = true && that.isSetIncomingCallTime();
    if (this_present_incomingCallTime || that_present_incomingCallTime) {
      if (!(this_present_incomingCallTime && that_present_incomingCallTime))
        return false;
      if (this.incomingCallTime != that.incomingCallTime)
        return false;
    }

    boolean this_present_outgoingCallTime = true && this.isSetOutgoingCallTime();
    boolean that_present_outgoingCallTime = true && that.isSetOutgoingCallTime();
    if (this_present_outgoingCallTime || that_present_outgoingCallTime) {
      if (!(this_present_outgoingCallTime && that_present_outgoingCallTime))
        return false;
      if (this.outgoingCallTime != that.outgoingCallTime)
        return false;
    }

    boolean this_present_nonCallTime = true && this.isSetNonCallTime();
    boolean that_present_nonCallTime = true && that.isSetNonCallTime();
    if (this_present_nonCallTime || that_present_nonCallTime) {
      if (!(this_present_nonCallTime && that_present_nonCallTime))
        return false;
      if (this.nonCallTime != that.nonCallTime)
        return false;
    }

    boolean this_present_callStatus = true && this.isSetCallStatus();
    boolean that_present_callStatus = true && that.isSetCallStatus();
    if (this_present_callStatus || that_present_callStatus) {
      if (!(this_present_callStatus && that_present_callStatus))
        return false;
      if (!this.callStatus.equals(that.callStatus))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetIncomingCallTime()) ? 131071 : 524287);
    if (isSetIncomingCallTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(incomingCallTime);

    hashCode = hashCode * 8191 + ((isSetOutgoingCallTime()) ? 131071 : 524287);
    if (isSetOutgoingCallTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(outgoingCallTime);

    hashCode = hashCode * 8191 + ((isSetNonCallTime()) ? 131071 : 524287);
    if (isSetNonCallTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(nonCallTime);

    hashCode = hashCode * 8191 + ((isSetCallStatus()) ? 131071 : 524287);
    if (isSetCallStatus())
      hashCode = hashCode * 8191 + callStatus.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(CallInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetIncomingCallTime()).compareTo(other.isSetIncomingCallTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIncomingCallTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.incomingCallTime, other.incomingCallTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetOutgoingCallTime()).compareTo(other.isSetOutgoingCallTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOutgoingCallTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.outgoingCallTime, other.outgoingCallTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetNonCallTime()).compareTo(other.isSetNonCallTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetNonCallTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nonCallTime, other.nonCallTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCallStatus()).compareTo(other.isSetCallStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCallStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.callStatus, other.callStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("CallInfo(");
    boolean first = true;

    if (isSetIncomingCallTime()) {
      sb.append("incomingCallTime:");
      sb.append(this.incomingCallTime);
      first = false;
    }
    if (isSetOutgoingCallTime()) {
      if (!first) sb.append(", ");
      sb.append("outgoingCallTime:");
      sb.append(this.outgoingCallTime);
      first = false;
    }
    if (isSetNonCallTime()) {
      if (!first) sb.append(", ");
      sb.append("nonCallTime:");
      sb.append(this.nonCallTime);
      first = false;
    }
    if (isSetCallStatus()) {
      if (!first) sb.append(", ");
      sb.append("callStatus:");
      if (this.callStatus == null) {
        sb.append("null");
      } else {
        sb.append(this.callStatus);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CallInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CallInfoStandardScheme getScheme() {
      return new CallInfoStandardScheme();
    }
  }

  private static class CallInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<CallInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CallInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INCOMING_CALL_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.incomingCallTime = iprot.readDouble();
              struct.setIncomingCallTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OUTGOING_CALL_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.outgoingCallTime = iprot.readDouble();
              struct.setOutgoingCallTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NON_CALL_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.nonCallTime = iprot.readDouble();
              struct.setNonCallTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // CALL_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.callStatus = iprot.readString();
              struct.setCallStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CallInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetIncomingCallTime()) {
        oprot.writeFieldBegin(INCOMING_CALL_TIME_FIELD_DESC);
        oprot.writeDouble(struct.incomingCallTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetOutgoingCallTime()) {
        oprot.writeFieldBegin(OUTGOING_CALL_TIME_FIELD_DESC);
        oprot.writeDouble(struct.outgoingCallTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetNonCallTime()) {
        oprot.writeFieldBegin(NON_CALL_TIME_FIELD_DESC);
        oprot.writeDouble(struct.nonCallTime);
        oprot.writeFieldEnd();
      }
      if (struct.callStatus != null) {
        if (struct.isSetCallStatus()) {
          oprot.writeFieldBegin(CALL_STATUS_FIELD_DESC);
          oprot.writeString(struct.callStatus);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CallInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CallInfoTupleScheme getScheme() {
      return new CallInfoTupleScheme();
    }
  }

  private static class CallInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<CallInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CallInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetIncomingCallTime()) {
        optionals.set(0);
      }
      if (struct.isSetOutgoingCallTime()) {
        optionals.set(1);
      }
      if (struct.isSetNonCallTime()) {
        optionals.set(2);
      }
      if (struct.isSetCallStatus()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetIncomingCallTime()) {
        oprot.writeDouble(struct.incomingCallTime);
      }
      if (struct.isSetOutgoingCallTime()) {
        oprot.writeDouble(struct.outgoingCallTime);
      }
      if (struct.isSetNonCallTime()) {
        oprot.writeDouble(struct.nonCallTime);
      }
      if (struct.isSetCallStatus()) {
        oprot.writeString(struct.callStatus);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CallInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.incomingCallTime = iprot.readDouble();
        struct.setIncomingCallTimeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.outgoingCallTime = iprot.readDouble();
        struct.setOutgoingCallTimeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.nonCallTime = iprot.readDouble();
        struct.setNonCallTimeIsSet(true);
      }
      if (incoming.get(3)) {
        struct.callStatus = iprot.readString();
        struct.setCallStatusIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

