/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.berkeley.cs.amplab.carat.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2018-2-13")
public class PackageProcess implements org.apache.thrift.TBase<PackageProcess, PackageProcess._Fields>, java.io.Serializable, Cloneable, Comparable<PackageProcess> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PackageProcess");

  private static final org.apache.thrift.protocol.TField PROCESS_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("processName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PROCESS_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("processCount", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField U_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("uId", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField SLEEPING_FIELD_DESC = new org.apache.thrift.protocol.TField("sleeping", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField FOREGROUND_FIELD_DESC = new org.apache.thrift.protocol.TField("foreground", org.apache.thrift.protocol.TType.BOOL, (short)5);
  private static final org.apache.thrift.protocol.TField FOREGROUND_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("foregroundTime", org.apache.thrift.protocol.TType.DOUBLE, (short)6);
  private static final org.apache.thrift.protocol.TField LAUNCH_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("launchCount", org.apache.thrift.protocol.TType.DOUBLE, (short)7);
  private static final org.apache.thrift.protocol.TField IMPORTANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("importance", org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.thrift.protocol.TField CRASH_COUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("crashCount", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField LAST_START_SINCE_BOOT_FIELD_DESC = new org.apache.thrift.protocol.TField("lastStartSinceBoot", org.apache.thrift.protocol.TType.DOUBLE, (short)10);
  private static final org.apache.thrift.protocol.TField LAST_START_TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("lastStartTimestamp", org.apache.thrift.protocol.TType.DOUBLE, (short)11);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PackageProcessStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PackageProcessTupleSchemeFactory());
  }

  public String processName; // optional
  public int processCount; // optional
  public int uId; // optional
  public boolean sleeping; // optional
  public boolean foreground; // optional
  public double foregroundTime; // optional
  public double launchCount; // optional
  public int importance; // optional
  public int crashCount; // optional
  public double lastStartSinceBoot; // optional
  public double lastStartTimestamp; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PROCESS_NAME((short)1, "processName"),
    PROCESS_COUNT((short)2, "processCount"),
    U_ID((short)3, "uId"),
    SLEEPING((short)4, "sleeping"),
    FOREGROUND((short)5, "foreground"),
    FOREGROUND_TIME((short)6, "foregroundTime"),
    LAUNCH_COUNT((short)7, "launchCount"),
    IMPORTANCE((short)8, "importance"),
    CRASH_COUNT((short)9, "crashCount"),
    LAST_START_SINCE_BOOT((short)10, "lastStartSinceBoot"),
    LAST_START_TIMESTAMP((short)11, "lastStartTimestamp");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PROCESS_NAME
          return PROCESS_NAME;
        case 2: // PROCESS_COUNT
          return PROCESS_COUNT;
        case 3: // U_ID
          return U_ID;
        case 4: // SLEEPING
          return SLEEPING;
        case 5: // FOREGROUND
          return FOREGROUND;
        case 6: // FOREGROUND_TIME
          return FOREGROUND_TIME;
        case 7: // LAUNCH_COUNT
          return LAUNCH_COUNT;
        case 8: // IMPORTANCE
          return IMPORTANCE;
        case 9: // CRASH_COUNT
          return CRASH_COUNT;
        case 10: // LAST_START_SINCE_BOOT
          return LAST_START_SINCE_BOOT;
        case 11: // LAST_START_TIMESTAMP
          return LAST_START_TIMESTAMP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PROCESSCOUNT_ISSET_ID = 0;
  private static final int __UID_ISSET_ID = 1;
  private static final int __SLEEPING_ISSET_ID = 2;
  private static final int __FOREGROUND_ISSET_ID = 3;
  private static final int __FOREGROUNDTIME_ISSET_ID = 4;
  private static final int __LAUNCHCOUNT_ISSET_ID = 5;
  private static final int __IMPORTANCE_ISSET_ID = 6;
  private static final int __CRASHCOUNT_ISSET_ID = 7;
  private static final int __LASTSTARTSINCEBOOT_ISSET_ID = 8;
  private static final int __LASTSTARTTIMESTAMP_ISSET_ID = 9;
  private short __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.PROCESS_NAME,_Fields.PROCESS_COUNT,_Fields.U_ID,_Fields.SLEEPING,_Fields.FOREGROUND,_Fields.FOREGROUND_TIME,_Fields.LAUNCH_COUNT,_Fields.IMPORTANCE,_Fields.CRASH_COUNT,_Fields.LAST_START_SINCE_BOOT,_Fields.LAST_START_TIMESTAMP};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PROCESS_NAME, new org.apache.thrift.meta_data.FieldMetaData("processName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PROCESS_COUNT, new org.apache.thrift.meta_data.FieldMetaData("processCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.U_ID, new org.apache.thrift.meta_data.FieldMetaData("uId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SLEEPING, new org.apache.thrift.meta_data.FieldMetaData("sleeping", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.FOREGROUND, new org.apache.thrift.meta_data.FieldMetaData("foreground", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.FOREGROUND_TIME, new org.apache.thrift.meta_data.FieldMetaData("foregroundTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.LAUNCH_COUNT, new org.apache.thrift.meta_data.FieldMetaData("launchCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.IMPORTANCE, new org.apache.thrift.meta_data.FieldMetaData("importance", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CRASH_COUNT, new org.apache.thrift.meta_data.FieldMetaData("crashCount", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.LAST_START_SINCE_BOOT, new org.apache.thrift.meta_data.FieldMetaData("lastStartSinceBoot", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.LAST_START_TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("lastStartTimestamp", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PackageProcess.class, metaDataMap);
  }

  public PackageProcess() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PackageProcess(PackageProcess other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetProcessName()) {
      this.processName = other.processName;
    }
    this.processCount = other.processCount;
    this.uId = other.uId;
    this.sleeping = other.sleeping;
    this.foreground = other.foreground;
    this.foregroundTime = other.foregroundTime;
    this.launchCount = other.launchCount;
    this.importance = other.importance;
    this.crashCount = other.crashCount;
    this.lastStartSinceBoot = other.lastStartSinceBoot;
    this.lastStartTimestamp = other.lastStartTimestamp;
  }

  public PackageProcess deepCopy() {
    return new PackageProcess(this);
  }

  @Override
  public void clear() {
    this.processName = null;
    setProcessCountIsSet(false);
    this.processCount = 0;
    setUIdIsSet(false);
    this.uId = 0;
    setSleepingIsSet(false);
    this.sleeping = false;
    setForegroundIsSet(false);
    this.foreground = false;
    setForegroundTimeIsSet(false);
    this.foregroundTime = 0.0;
    setLaunchCountIsSet(false);
    this.launchCount = 0.0;
    setImportanceIsSet(false);
    this.importance = 0;
    setCrashCountIsSet(false);
    this.crashCount = 0;
    setLastStartSinceBootIsSet(false);
    this.lastStartSinceBoot = 0.0;
    setLastStartTimestampIsSet(false);
    this.lastStartTimestamp = 0.0;
  }

  public String getProcessName() {
    return this.processName;
  }

  public PackageProcess setProcessName(String processName) {
    this.processName = processName;
    return this;
  }

  public void unsetProcessName() {
    this.processName = null;
  }

  /** Returns true if field processName is set (has been assigned a value) and false otherwise */
  public boolean isSetProcessName() {
    return this.processName != null;
  }

  public void setProcessNameIsSet(boolean value) {
    if (!value) {
      this.processName = null;
    }
  }

  public int getProcessCount() {
    return this.processCount;
  }

  public PackageProcess setProcessCount(int processCount) {
    this.processCount = processCount;
    setProcessCountIsSet(true);
    return this;
  }

  public void unsetProcessCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __PROCESSCOUNT_ISSET_ID);
  }

  /** Returns true if field processCount is set (has been assigned a value) and false otherwise */
  public boolean isSetProcessCount() {
    return EncodingUtils.testBit(__isset_bitfield, __PROCESSCOUNT_ISSET_ID);
  }

  public void setProcessCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __PROCESSCOUNT_ISSET_ID, value);
  }

  public int getUId() {
    return this.uId;
  }

  public PackageProcess setUId(int uId) {
    this.uId = uId;
    setUIdIsSet(true);
    return this;
  }

  public void unsetUId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __UID_ISSET_ID);
  }

  /** Returns true if field uId is set (has been assigned a value) and false otherwise */
  public boolean isSetUId() {
    return EncodingUtils.testBit(__isset_bitfield, __UID_ISSET_ID);
  }

  public void setUIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __UID_ISSET_ID, value);
  }

  public boolean isSleeping() {
    return this.sleeping;
  }

  public PackageProcess setSleeping(boolean sleeping) {
    this.sleeping = sleeping;
    setSleepingIsSet(true);
    return this;
  }

  public void unsetSleeping() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SLEEPING_ISSET_ID);
  }

  /** Returns true if field sleeping is set (has been assigned a value) and false otherwise */
  public boolean isSetSleeping() {
    return EncodingUtils.testBit(__isset_bitfield, __SLEEPING_ISSET_ID);
  }

  public void setSleepingIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SLEEPING_ISSET_ID, value);
  }

  public boolean isForeground() {
    return this.foreground;
  }

  public PackageProcess setForeground(boolean foreground) {
    this.foreground = foreground;
    setForegroundIsSet(true);
    return this;
  }

  public void unsetForeground() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FOREGROUND_ISSET_ID);
  }

  /** Returns true if field foreground is set (has been assigned a value) and false otherwise */
  public boolean isSetForeground() {
    return EncodingUtils.testBit(__isset_bitfield, __FOREGROUND_ISSET_ID);
  }

  public void setForegroundIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FOREGROUND_ISSET_ID, value);
  }

  public double getForegroundTime() {
    return this.foregroundTime;
  }

  public PackageProcess setForegroundTime(double foregroundTime) {
    this.foregroundTime = foregroundTime;
    setForegroundTimeIsSet(true);
    return this;
  }

  public void unsetForegroundTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FOREGROUNDTIME_ISSET_ID);
  }

  /** Returns true if field foregroundTime is set (has been assigned a value) and false otherwise */
  public boolean isSetForegroundTime() {
    return EncodingUtils.testBit(__isset_bitfield, __FOREGROUNDTIME_ISSET_ID);
  }

  public void setForegroundTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FOREGROUNDTIME_ISSET_ID, value);
  }

  public double getLaunchCount() {
    return this.launchCount;
  }

  public PackageProcess setLaunchCount(double launchCount) {
    this.launchCount = launchCount;
    setLaunchCountIsSet(true);
    return this;
  }

  public void unsetLaunchCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LAUNCHCOUNT_ISSET_ID);
  }

  /** Returns true if field launchCount is set (has been assigned a value) and false otherwise */
  public boolean isSetLaunchCount() {
    return EncodingUtils.testBit(__isset_bitfield, __LAUNCHCOUNT_ISSET_ID);
  }

  public void setLaunchCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LAUNCHCOUNT_ISSET_ID, value);
  }

  public int getImportance() {
    return this.importance;
  }

  public PackageProcess setImportance(int importance) {
    this.importance = importance;
    setImportanceIsSet(true);
    return this;
  }

  public void unsetImportance() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __IMPORTANCE_ISSET_ID);
  }

  /** Returns true if field importance is set (has been assigned a value) and false otherwise */
  public boolean isSetImportance() {
    return EncodingUtils.testBit(__isset_bitfield, __IMPORTANCE_ISSET_ID);
  }

  public void setImportanceIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __IMPORTANCE_ISSET_ID, value);
  }

  public int getCrashCount() {
    return this.crashCount;
  }

  public PackageProcess setCrashCount(int crashCount) {
    this.crashCount = crashCount;
    setCrashCountIsSet(true);
    return this;
  }

  public void unsetCrashCount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CRASHCOUNT_ISSET_ID);
  }

  /** Returns true if field crashCount is set (has been assigned a value) and false otherwise */
  public boolean isSetCrashCount() {
    return EncodingUtils.testBit(__isset_bitfield, __CRASHCOUNT_ISSET_ID);
  }

  public void setCrashCountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CRASHCOUNT_ISSET_ID, value);
  }

  public double getLastStartSinceBoot() {
    return this.lastStartSinceBoot;
  }

  public PackageProcess setLastStartSinceBoot(double lastStartSinceBoot) {
    this.lastStartSinceBoot = lastStartSinceBoot;
    setLastStartSinceBootIsSet(true);
    return this;
  }

  public void unsetLastStartSinceBoot() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTSTARTSINCEBOOT_ISSET_ID);
  }

  /** Returns true if field lastStartSinceBoot is set (has been assigned a value) and false otherwise */
  public boolean isSetLastStartSinceBoot() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTSTARTSINCEBOOT_ISSET_ID);
  }

  public void setLastStartSinceBootIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTSTARTSINCEBOOT_ISSET_ID, value);
  }

  public double getLastStartTimestamp() {
    return this.lastStartTimestamp;
  }

  public PackageProcess setLastStartTimestamp(double lastStartTimestamp) {
    this.lastStartTimestamp = lastStartTimestamp;
    setLastStartTimestampIsSet(true);
    return this;
  }

  public void unsetLastStartTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __LASTSTARTTIMESTAMP_ISSET_ID);
  }

  /** Returns true if field lastStartTimestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetLastStartTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __LASTSTARTTIMESTAMP_ISSET_ID);
  }

  public void setLastStartTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __LASTSTARTTIMESTAMP_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PROCESS_NAME:
      if (value == null) {
        unsetProcessName();
      } else {
        setProcessName((String)value);
      }
      break;

    case PROCESS_COUNT:
      if (value == null) {
        unsetProcessCount();
      } else {
        setProcessCount((Integer)value);
      }
      break;

    case U_ID:
      if (value == null) {
        unsetUId();
      } else {
        setUId((Integer)value);
      }
      break;

    case SLEEPING:
      if (value == null) {
        unsetSleeping();
      } else {
        setSleeping((Boolean)value);
      }
      break;

    case FOREGROUND:
      if (value == null) {
        unsetForeground();
      } else {
        setForeground((Boolean)value);
      }
      break;

    case FOREGROUND_TIME:
      if (value == null) {
        unsetForegroundTime();
      } else {
        setForegroundTime((Double)value);
      }
      break;

    case LAUNCH_COUNT:
      if (value == null) {
        unsetLaunchCount();
      } else {
        setLaunchCount((Double)value);
      }
      break;

    case IMPORTANCE:
      if (value == null) {
        unsetImportance();
      } else {
        setImportance((Integer)value);
      }
      break;

    case CRASH_COUNT:
      if (value == null) {
        unsetCrashCount();
      } else {
        setCrashCount((Integer)value);
      }
      break;

    case LAST_START_SINCE_BOOT:
      if (value == null) {
        unsetLastStartSinceBoot();
      } else {
        setLastStartSinceBoot((Double)value);
      }
      break;

    case LAST_START_TIMESTAMP:
      if (value == null) {
        unsetLastStartTimestamp();
      } else {
        setLastStartTimestamp((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PROCESS_NAME:
      return getProcessName();

    case PROCESS_COUNT:
      return Integer.valueOf(getProcessCount());

    case U_ID:
      return Integer.valueOf(getUId());

    case SLEEPING:
      return Boolean.valueOf(isSleeping());

    case FOREGROUND:
      return Boolean.valueOf(isForeground());

    case FOREGROUND_TIME:
      return Double.valueOf(getForegroundTime());

    case LAUNCH_COUNT:
      return Double.valueOf(getLaunchCount());

    case IMPORTANCE:
      return Integer.valueOf(getImportance());

    case CRASH_COUNT:
      return Integer.valueOf(getCrashCount());

    case LAST_START_SINCE_BOOT:
      return Double.valueOf(getLastStartSinceBoot());

    case LAST_START_TIMESTAMP:
      return Double.valueOf(getLastStartTimestamp());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PROCESS_NAME:
      return isSetProcessName();
    case PROCESS_COUNT:
      return isSetProcessCount();
    case U_ID:
      return isSetUId();
    case SLEEPING:
      return isSetSleeping();
    case FOREGROUND:
      return isSetForeground();
    case FOREGROUND_TIME:
      return isSetForegroundTime();
    case LAUNCH_COUNT:
      return isSetLaunchCount();
    case IMPORTANCE:
      return isSetImportance();
    case CRASH_COUNT:
      return isSetCrashCount();
    case LAST_START_SINCE_BOOT:
      return isSetLastStartSinceBoot();
    case LAST_START_TIMESTAMP:
      return isSetLastStartTimestamp();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PackageProcess)
      return this.equals((PackageProcess)that);
    return false;
  }

  public boolean equals(PackageProcess that) {
    if (that == null)
      return false;

    boolean this_present_processName = true && this.isSetProcessName();
    boolean that_present_processName = true && that.isSetProcessName();
    if (this_present_processName || that_present_processName) {
      if (!(this_present_processName && that_present_processName))
        return false;
      if (!this.processName.equals(that.processName))
        return false;
    }

    boolean this_present_processCount = true && this.isSetProcessCount();
    boolean that_present_processCount = true && that.isSetProcessCount();
    if (this_present_processCount || that_present_processCount) {
      if (!(this_present_processCount && that_present_processCount))
        return false;
      if (this.processCount != that.processCount)
        return false;
    }

    boolean this_present_uId = true && this.isSetUId();
    boolean that_present_uId = true && that.isSetUId();
    if (this_present_uId || that_present_uId) {
      if (!(this_present_uId && that_present_uId))
        return false;
      if (this.uId != that.uId)
        return false;
    }

    boolean this_present_sleeping = true && this.isSetSleeping();
    boolean that_present_sleeping = true && that.isSetSleeping();
    if (this_present_sleeping || that_present_sleeping) {
      if (!(this_present_sleeping && that_present_sleeping))
        return false;
      if (this.sleeping != that.sleeping)
        return false;
    }

    boolean this_present_foreground = true && this.isSetForeground();
    boolean that_present_foreground = true && that.isSetForeground();
    if (this_present_foreground || that_present_foreground) {
      if (!(this_present_foreground && that_present_foreground))
        return false;
      if (this.foreground != that.foreground)
        return false;
    }

    boolean this_present_foregroundTime = true && this.isSetForegroundTime();
    boolean that_present_foregroundTime = true && that.isSetForegroundTime();
    if (this_present_foregroundTime || that_present_foregroundTime) {
      if (!(this_present_foregroundTime && that_present_foregroundTime))
        return false;
      if (this.foregroundTime != that.foregroundTime)
        return false;
    }

    boolean this_present_launchCount = true && this.isSetLaunchCount();
    boolean that_present_launchCount = true && that.isSetLaunchCount();
    if (this_present_launchCount || that_present_launchCount) {
      if (!(this_present_launchCount && that_present_launchCount))
        return false;
      if (this.launchCount != that.launchCount)
        return false;
    }

    boolean this_present_importance = true && this.isSetImportance();
    boolean that_present_importance = true && that.isSetImportance();
    if (this_present_importance || that_present_importance) {
      if (!(this_present_importance && that_present_importance))
        return false;
      if (this.importance != that.importance)
        return false;
    }

    boolean this_present_crashCount = true && this.isSetCrashCount();
    boolean that_present_crashCount = true && that.isSetCrashCount();
    if (this_present_crashCount || that_present_crashCount) {
      if (!(this_present_crashCount && that_present_crashCount))
        return false;
      if (this.crashCount != that.crashCount)
        return false;
    }

    boolean this_present_lastStartSinceBoot = true && this.isSetLastStartSinceBoot();
    boolean that_present_lastStartSinceBoot = true && that.isSetLastStartSinceBoot();
    if (this_present_lastStartSinceBoot || that_present_lastStartSinceBoot) {
      if (!(this_present_lastStartSinceBoot && that_present_lastStartSinceBoot))
        return false;
      if (this.lastStartSinceBoot != that.lastStartSinceBoot)
        return false;
    }

    boolean this_present_lastStartTimestamp = true && this.isSetLastStartTimestamp();
    boolean that_present_lastStartTimestamp = true && that.isSetLastStartTimestamp();
    if (this_present_lastStartTimestamp || that_present_lastStartTimestamp) {
      if (!(this_present_lastStartTimestamp && that_present_lastStartTimestamp))
        return false;
      if (this.lastStartTimestamp != that.lastStartTimestamp)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_processName = true && (isSetProcessName());
    list.add(present_processName);
    if (present_processName)
      list.add(processName);

    boolean present_processCount = true && (isSetProcessCount());
    list.add(present_processCount);
    if (present_processCount)
      list.add(processCount);

    boolean present_uId = true && (isSetUId());
    list.add(present_uId);
    if (present_uId)
      list.add(uId);

    boolean present_sleeping = true && (isSetSleeping());
    list.add(present_sleeping);
    if (present_sleeping)
      list.add(sleeping);

    boolean present_foreground = true && (isSetForeground());
    list.add(present_foreground);
    if (present_foreground)
      list.add(foreground);

    boolean present_foregroundTime = true && (isSetForegroundTime());
    list.add(present_foregroundTime);
    if (present_foregroundTime)
      list.add(foregroundTime);

    boolean present_launchCount = true && (isSetLaunchCount());
    list.add(present_launchCount);
    if (present_launchCount)
      list.add(launchCount);

    boolean present_importance = true && (isSetImportance());
    list.add(present_importance);
    if (present_importance)
      list.add(importance);

    boolean present_crashCount = true && (isSetCrashCount());
    list.add(present_crashCount);
    if (present_crashCount)
      list.add(crashCount);

    boolean present_lastStartSinceBoot = true && (isSetLastStartSinceBoot());
    list.add(present_lastStartSinceBoot);
    if (present_lastStartSinceBoot)
      list.add(lastStartSinceBoot);

    boolean present_lastStartTimestamp = true && (isSetLastStartTimestamp());
    list.add(present_lastStartTimestamp);
    if (present_lastStartTimestamp)
      list.add(lastStartTimestamp);

    return list.hashCode();
  }

  @Override
  public int compareTo(PackageProcess other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetProcessName()).compareTo(other.isSetProcessName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcessName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.processName, other.processName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProcessCount()).compareTo(other.isSetProcessCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProcessCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.processCount, other.processCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUId()).compareTo(other.isSetUId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uId, other.uId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSleeping()).compareTo(other.isSetSleeping());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSleeping()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sleeping, other.sleeping);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetForeground()).compareTo(other.isSetForeground());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetForeground()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.foreground, other.foreground);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetForegroundTime()).compareTo(other.isSetForegroundTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetForegroundTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.foregroundTime, other.foregroundTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLaunchCount()).compareTo(other.isSetLaunchCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLaunchCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.launchCount, other.launchCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetImportance()).compareTo(other.isSetImportance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImportance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.importance, other.importance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCrashCount()).compareTo(other.isSetCrashCount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCrashCount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.crashCount, other.crashCount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastStartSinceBoot()).compareTo(other.isSetLastStartSinceBoot());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastStartSinceBoot()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastStartSinceBoot, other.lastStartSinceBoot);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetLastStartTimestamp()).compareTo(other.isSetLastStartTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLastStartTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.lastStartTimestamp, other.lastStartTimestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PackageProcess(");
    boolean first = true;

    if (isSetProcessName()) {
      sb.append("processName:");
      if (this.processName == null) {
        sb.append("null");
      } else {
        sb.append(this.processName);
      }
      first = false;
    }
    if (isSetProcessCount()) {
      if (!first) sb.append(", ");
      sb.append("processCount:");
      sb.append(this.processCount);
      first = false;
    }
    if (isSetUId()) {
      if (!first) sb.append(", ");
      sb.append("uId:");
      sb.append(this.uId);
      first = false;
    }
    if (isSetSleeping()) {
      if (!first) sb.append(", ");
      sb.append("sleeping:");
      sb.append(this.sleeping);
      first = false;
    }
    if (isSetForeground()) {
      if (!first) sb.append(", ");
      sb.append("foreground:");
      sb.append(this.foreground);
      first = false;
    }
    if (isSetForegroundTime()) {
      if (!first) sb.append(", ");
      sb.append("foregroundTime:");
      sb.append(this.foregroundTime);
      first = false;
    }
    if (isSetLaunchCount()) {
      if (!first) sb.append(", ");
      sb.append("launchCount:");
      sb.append(this.launchCount);
      first = false;
    }
    if (isSetImportance()) {
      if (!first) sb.append(", ");
      sb.append("importance:");
      sb.append(this.importance);
      first = false;
    }
    if (isSetCrashCount()) {
      if (!first) sb.append(", ");
      sb.append("crashCount:");
      sb.append(this.crashCount);
      first = false;
    }
    if (isSetLastStartSinceBoot()) {
      if (!first) sb.append(", ");
      sb.append("lastStartSinceBoot:");
      sb.append(this.lastStartSinceBoot);
      first = false;
    }
    if (isSetLastStartTimestamp()) {
      if (!first) sb.append(", ");
      sb.append("lastStartTimestamp:");
      sb.append(this.lastStartTimestamp);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PackageProcessStandardSchemeFactory implements SchemeFactory {
    public PackageProcessStandardScheme getScheme() {
      return new PackageProcessStandardScheme();
    }
  }

  private static class PackageProcessStandardScheme extends StandardScheme<PackageProcess> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PackageProcess struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PROCESS_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.processName = iprot.readString();
              struct.setProcessNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PROCESS_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.processCount = iprot.readI32();
              struct.setProcessCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // U_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.uId = iprot.readI32();
              struct.setUIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SLEEPING
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.sleeping = iprot.readBool();
              struct.setSleepingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // FOREGROUND
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.foreground = iprot.readBool();
              struct.setForegroundIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // FOREGROUND_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.foregroundTime = iprot.readDouble();
              struct.setForegroundTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // LAUNCH_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.launchCount = iprot.readDouble();
              struct.setLaunchCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // IMPORTANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.importance = iprot.readI32();
              struct.setImportanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // CRASH_COUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.crashCount = iprot.readI32();
              struct.setCrashCountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // LAST_START_SINCE_BOOT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.lastStartSinceBoot = iprot.readDouble();
              struct.setLastStartSinceBootIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // LAST_START_TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.lastStartTimestamp = iprot.readDouble();
              struct.setLastStartTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PackageProcess struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.processName != null) {
        if (struct.isSetProcessName()) {
          oprot.writeFieldBegin(PROCESS_NAME_FIELD_DESC);
          oprot.writeString(struct.processName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetProcessCount()) {
        oprot.writeFieldBegin(PROCESS_COUNT_FIELD_DESC);
        oprot.writeI32(struct.processCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetUId()) {
        oprot.writeFieldBegin(U_ID_FIELD_DESC);
        oprot.writeI32(struct.uId);
        oprot.writeFieldEnd();
      }
      if (struct.isSetSleeping()) {
        oprot.writeFieldBegin(SLEEPING_FIELD_DESC);
        oprot.writeBool(struct.sleeping);
        oprot.writeFieldEnd();
      }
      if (struct.isSetForeground()) {
        oprot.writeFieldBegin(FOREGROUND_FIELD_DESC);
        oprot.writeBool(struct.foreground);
        oprot.writeFieldEnd();
      }
      if (struct.isSetForegroundTime()) {
        oprot.writeFieldBegin(FOREGROUND_TIME_FIELD_DESC);
        oprot.writeDouble(struct.foregroundTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLaunchCount()) {
        oprot.writeFieldBegin(LAUNCH_COUNT_FIELD_DESC);
        oprot.writeDouble(struct.launchCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetImportance()) {
        oprot.writeFieldBegin(IMPORTANCE_FIELD_DESC);
        oprot.writeI32(struct.importance);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCrashCount()) {
        oprot.writeFieldBegin(CRASH_COUNT_FIELD_DESC);
        oprot.writeI32(struct.crashCount);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLastStartSinceBoot()) {
        oprot.writeFieldBegin(LAST_START_SINCE_BOOT_FIELD_DESC);
        oprot.writeDouble(struct.lastStartSinceBoot);
        oprot.writeFieldEnd();
      }
      if (struct.isSetLastStartTimestamp()) {
        oprot.writeFieldBegin(LAST_START_TIMESTAMP_FIELD_DESC);
        oprot.writeDouble(struct.lastStartTimestamp);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PackageProcessTupleSchemeFactory implements SchemeFactory {
    public PackageProcessTupleScheme getScheme() {
      return new PackageProcessTupleScheme();
    }
  }

  private static class PackageProcessTupleScheme extends TupleScheme<PackageProcess> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PackageProcess struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetProcessName()) {
        optionals.set(0);
      }
      if (struct.isSetProcessCount()) {
        optionals.set(1);
      }
      if (struct.isSetUId()) {
        optionals.set(2);
      }
      if (struct.isSetSleeping()) {
        optionals.set(3);
      }
      if (struct.isSetForeground()) {
        optionals.set(4);
      }
      if (struct.isSetForegroundTime()) {
        optionals.set(5);
      }
      if (struct.isSetLaunchCount()) {
        optionals.set(6);
      }
      if (struct.isSetImportance()) {
        optionals.set(7);
      }
      if (struct.isSetCrashCount()) {
        optionals.set(8);
      }
      if (struct.isSetLastStartSinceBoot()) {
        optionals.set(9);
      }
      if (struct.isSetLastStartTimestamp()) {
        optionals.set(10);
      }
      oprot.writeBitSet(optionals, 11);
      if (struct.isSetProcessName()) {
        oprot.writeString(struct.processName);
      }
      if (struct.isSetProcessCount()) {
        oprot.writeI32(struct.processCount);
      }
      if (struct.isSetUId()) {
        oprot.writeI32(struct.uId);
      }
      if (struct.isSetSleeping()) {
        oprot.writeBool(struct.sleeping);
      }
      if (struct.isSetForeground()) {
        oprot.writeBool(struct.foreground);
      }
      if (struct.isSetForegroundTime()) {
        oprot.writeDouble(struct.foregroundTime);
      }
      if (struct.isSetLaunchCount()) {
        oprot.writeDouble(struct.launchCount);
      }
      if (struct.isSetImportance()) {
        oprot.writeI32(struct.importance);
      }
      if (struct.isSetCrashCount()) {
        oprot.writeI32(struct.crashCount);
      }
      if (struct.isSetLastStartSinceBoot()) {
        oprot.writeDouble(struct.lastStartSinceBoot);
      }
      if (struct.isSetLastStartTimestamp()) {
        oprot.writeDouble(struct.lastStartTimestamp);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PackageProcess struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(11);
      if (incoming.get(0)) {
        struct.processName = iprot.readString();
        struct.setProcessNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.processCount = iprot.readI32();
        struct.setProcessCountIsSet(true);
      }
      if (incoming.get(2)) {
        struct.uId = iprot.readI32();
        struct.setUIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.sleeping = iprot.readBool();
        struct.setSleepingIsSet(true);
      }
      if (incoming.get(4)) {
        struct.foreground = iprot.readBool();
        struct.setForegroundIsSet(true);
      }
      if (incoming.get(5)) {
        struct.foregroundTime = iprot.readDouble();
        struct.setForegroundTimeIsSet(true);
      }
      if (incoming.get(6)) {
        struct.launchCount = iprot.readDouble();
        struct.setLaunchCountIsSet(true);
      }
      if (incoming.get(7)) {
        struct.importance = iprot.readI32();
        struct.setImportanceIsSet(true);
      }
      if (incoming.get(8)) {
        struct.crashCount = iprot.readI32();
        struct.setCrashCountIsSet(true);
      }
      if (incoming.get(9)) {
        struct.lastStartSinceBoot = iprot.readDouble();
        struct.setLastStartSinceBootIsSet(true);
      }
      if (incoming.get(10)) {
        struct.lastStartTimestamp = iprot.readDouble();
        struct.setLastStartTimestampIsSet(true);
      }
    }
  }

}

